service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
  createCertificate:
    handler: api/create.certificate
    environment:
      CERTIFICATE_TABLE_NAME: !Ref certificateTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLE: 1
    iamRoleStatements:
      - Effect : "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt certificateTable.Arn
    events:
      - http:
          method: post
          path: certificateList
          cors:
            origin: "*"
            headers: ${self.custom.allowedHeaders}

resources:
  Resources:
    certificateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: certificateTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: certificate_id
            AttributeType: S
        KeySchema:
          - AttributeName: certificate_id
            KeyType: HASH